export const provinces: Record<string, string[]> = {
  'Metro Manila': [
    'Caloocan', 'Las Piñas', 'Makati', 'Malabon', 'Mandaluyong', 'Manila',
    'Marikina', 'Muntinlupa', 'Navotas', 'Parañaque', 'Pasay', 'Pasig',
    'Pateros', 'Quezon City', 'San Juan', 'Taguig', 'Valenzuela',
  ],
  'Abra': [
    'Bangued', 'Boliney', 'Bucay', 'Bucloc', 'Daguioman', 'Danglas',
    'Dolores', 'La Paz', 'Lacub', 'Lagangilang', 'Lagayan', 'Langiden',
    'Licuan-Baay', 'Luba', 'Malibcong', 'Manabo', 'Peñarrubia', 'Pidigan',
    'Pilar', 'Sallapadan', 'San Isidro', 'San Juan', 'San Quintin', 'Tayum',
    'Tineg', 'Tubo', 'Villaviciosa',
  ],
  'Agusan del Norte': [
    'Butuan City', 'Cabadbaran City', 'Buenavista', 'Carmen', 'Jabonga',
    'Kitcharao', 'Las Nieves', 'Magallanes', 'Nasipit', 'Remedios T. Romualdez',
    'Santiago', 'Tubay',
  ],
  'Agusan del Sur': [
    'Bayugan City', 'Bunawan', 'Esperanza', 'La Paz', 'Loreto',
    'Prosperidad', 'Rosario', 'San Francisco', 'San Luis', 'Santa Josefa',
    'Sibagat', 'Talacogon', 'Trento', 'Veruela',
  ],
  'Aklan': [
    'Altavas', 'Balete', 'Banga', 'Batan', 'Buruanga', 'Ibajay', 'Kalibo',
    'Lezo', 'Libacao', 'Madalag', 'Makato', 'Malay', 'Malinao', 'Nabas',
    'New Washington', 'Numancia', 'Tangalan',
  ],
  'Albay': [
    'Legazpi City', 'Ligao City', 'Tabaco City', 'Bacacay', 'Camalig',
    'Daraga', 'Guinobatan', 'Jovellar', 'Libon', 'Malilipot', 'Malinao',
    'Manito', 'Oas', 'Pio Duran', 'Polangui', 'Rapu-Rapu', 'Santo Domingo',
    'Tiwi',
  ],
  'Antique': [
    'San Jose de Buenavista', 'Anini-y', 'Barbaza', 'Belison', 'Bugasong',
    'Caluya', 'Culasi', 'Hamtic', 'Laua-an', 'Libertad', 'Pandan', 'Patnongon',
    'San Remigio', 'Sebaste', 'Sibalom', 'Tibiao', 'Tobias Fornier', 'Valderrama',
  ],
  'Apayao': [
    'Calanasan', 'Conner', 'Flora', 'Kabugao', 'Luna', 'Pudtol', 'Santa Marcela',
  ],
  'Aurora': [
    'Baler', 'Casiguran', 'Dilasag', 'Dinalungan', 'Dingalan', 'Dipaculao',
    'Maria Aurora', 'San Luis',
  ],
  'Basilan': [
    'Isabela City', 'Akbar', 'Al-Barka', 'Hadji Mohammad Ajul', 'Hadji Muhtamad',
    'Lamitan City', 'Lantawan', 'Maluso', 'Sumisip', 'Tipo-Tipo', 'Tuburan', 'Ungkaya Pukan',
  ],
  'Bataan': [
    'Balanga City', 'Abucay', 'Bagac', 'Dinalupihan', 'Hermosa', 'Limay',
    'Mariveles', 'Morong', 'Orani', 'Orion', 'Pilar', 'Samal',
  ],
  'Batanes': [
    'Basco', 'Itbayat', 'Ivana', 'Mahatao', 'Sabtang', 'Uyugan',
  ],
  'Batangas': [
    'Batangas City', 'Lipa City', 'Tanauan City', 'Agoncillo', 'Alitagtag',
    'Balayan', 'Balete', 'Bauan', 'Calaca', 'Calatagan', 'Cuenca', 'Ibaan',
    'Laurel', 'Lemery', 'Lian', 'Lobo', 'Mabini', 'Malvar', 'Mataas na Kahoy',
    'Nasugbu', 'Padre Garcia', 'Rosario', 'San Jose', 'San Juan', 'San Luis',
    'San Nicolas', 'San Pascual', 'Santa Teresita', 'Santo Tomas', 'Taal',
    'Talisay', 'Tingloy', 'Tuy',
  ],
  'Benguet': [
    'Baguio City', 'Atok', 'Bakun', 'Bokod', 'Buguias', 'Itogon',
    'Kabayan', 'Kapangan', 'Kibungan', 'La Trinidad', 'Mankayan', 'Sablan',
    'Tuba', 'Tublay',
  ],
  'Biliran': [
    'Naval', 'Almeria', 'Biliran', 'Cabucgayan', 'Caibiran', 'Culaba', 'Kawayan', 'Maripipi',
  ],
  'Bohol': [
    'Tagbilaran City', 'Alburquerque', 'Alicia', 'Anda', 'Antequera',
    'Baclayon', 'Balilihan', 'Batuan', 'Bilar', 'Buenavista', 'Calape',
    'Candijay', 'Carmen', 'Catigbian', 'Clarin', 'Corella', 'Cortes',
    'Dagohoy', 'Danao', 'Dauis', 'Dimiao', 'Duero', 'Garcia Hernandez',
    'Getafe', 'Guindulman', 'Inabanga', 'Jagna', 'Lila', 'Loay', 'Loboc',
    'Loon', 'Mabini', 'Maribojoc', 'Panglao', 'Pilar', 'President Carlos P. Garcia',
    'Sagbayan', 'San Isidro', 'San Miguel', 'Sevilla', 'Sierra Bullones',
    'Sikatuna', 'Talibon', 'Trinidad', 'Tubigon', 'Ubay', 'Valencia',
  ],
  'Bukidnon': [
    'Malaybalay City', 'Valencia City', 'Baungon', 'Cabanglasan', 'Damulog',
    'Dangcagan', 'Don Carlos', 'Impasugong', 'Kadingilan', 'Kalilangan',
    'Kibawe', 'Kitaotao', 'Lantapan', 'Libona', 'Malitbog', 'Manolo Fortich',
    'Maramag', 'Pangantucan', 'Quezon', 'San Fernando', 'Sumilao', 'Talakag',
  ],
  'Bulacan': [
    'Malolos City', 'Meycauayan City', 'San Jose del Monte City',
    'Angat', 'Balagtas', 'Baliuag', 'Bocaue', 'Bulakan', 'Bustos', 'Calumpit',
    'Doña Remedios Trinidad', 'Guiguinto', 'Hagonoy', 'Marilao', 'Norzagaray',
    'Obando', 'Pandi', 'Paombong', 'Plaridel', 'Pulilan', 'San Ildefonso',
    'San Miguel', 'San Rafael', 'Santa Maria',
  ],
  'Cagayan': [
    'Tuguegarao City', 'Abulug', 'Alcala', 'Allacapan', 'Amulung', 'Aparri',
    'Baggao', 'Ballesteros', 'Buguey', 'Calayan', 'Camalaniugan', 'Claveria',
    'Enrile', 'Gattaran', 'Gonzaga', 'Iguig', 'Lal-lo', 'Lasam', 'Pamplona',
    'Peñablanca', 'Piat', 'Rizal', 'Sanchez-Mira', 'Santa Ana', 'Santa Praxedes',
    'Santa Teresita', 'Santo Niño', 'Solana', 'Tuao',
  ],
  'Camarines Norte': [
    'Daet', 'Basud', 'Capalonga', 'Jose Panganiban', 'Labo', 'Mercedes',
    'Paracale', 'San Lorenzo Ruiz', 'San Vicente', 'Santa Elena', 'Talisay',
    'Vinzons',
  ],
  'Camarines Sur': [
    'Naga City', 'Iriga City', 'Baao', 'Balatan', 'Bato', 'Bombon', 'Buhi',
    'Bula', 'Cabusao', 'Calabanga', 'Camaligan', 'Canaman', 'Caramoan',
    'Del Gallego', 'Gainza', 'Garchitorena', 'Goa', 'Lagonoy', 'Libmanan',
    'Lupi', 'Magarao', 'Milaor', 'Minalabac', 'Nabua', 'Ocampo', 'Pamplona',
    'Pasacao', 'Pili', 'Presentacion', 'Ragay', 'Sagñay', 'San Fernando',
    'San Jose', 'Sipocot', 'Siruma', 'Tigaon', 'Tinambac',
  ],
  'Camiguin': [
    'Mambajao', 'Catarman', 'Guinsiliban', 'Mahinog', 'Sagay',
  ],
  'Capiz': [
    'Roxas City', 'Cuartero', 'Dao', 'Dumalag', 'Dumarao', 'Ivisan',
    'Jamindan', 'Ma-ayon', 'Mambusao', 'Panay', 'Panitan', 'Pilar',
    'Pontevedra', 'President Roxas', 'Sapi-an', 'Sigma', 'Tapaz',
  ],
  'Catanduanes': [
    'Virac', 'Bagamanoc', 'Baras', 'Bato', 'Caramoran', 'Gigmoto',
    'Pandan', 'Panganiban', 'San Andres', 'San Miguel', 'Viga',
  ],
  'Cavite': [
    'Cavite City', 'Tagaytay City', 'Trece Martires City', 'Alfonso',
    'Amadeo', 'Bacoor City', 'Carmona', 'Dasmariñas City', 'General Emilio Aguinaldo',
    'General Mariano Alvarez', 'General Trias City', 'Imus City', 'Indang',
    'Kawit', 'Magallanes', 'Maragondon', 'Mendez', 'Naic', 'Noveleta',
    'Rosario', 'Silang', 'Tanza', 'Ternate',
  ],
  'Cebu': [
    'Cebu City', 'Mandaue City', 'Lapu-Lapu City', 'Carcar City', 'Danao City',
    'Naga City', 'Talisay City', 'Toledo City', 'Alcantara', 'Alcoy', 'Alegria',
    'Aloguinsan', 'Argao', 'Asturias', 'Badian', 'Balamban', 'Bantayan',
    'Barili', 'Bogo City', 'Boljoon', 'Borbon', 'Carmen', 'Catmon', 'Compostela',
    'Consolacion', 'Cordova', 'Dalaguete', 'Dumanjug', 'Ginatilan', 'Liloan',
    'Madridejos', 'Malabuyoc', 'Medellin', 'Minglanilla', 'Moalboal', 'Oslob',
    'Pilar', 'Pinamungajan', 'Poro', 'Ronda', 'Samboan', 'San Fernando',
    'San Francisco', 'San Remigio', 'Santa Fe', 'Santander', 'Sibonga',
    'Sogod', 'Tabogon', 'Tabuelan', 'Tuburan', 'Tudela',
  ],
  'Compostela Valley': [
    'Nabunturan', 'Compostela', 'Laak', 'Mabini', 'Maco', 'Maragusan',
    'Mawab', 'Monkayo', 'Montevista', 'New Bataan', 'Pantukan',
  ],
  'Cotabato (North Cotabato)': [
    'Kidapawan City', 'Alamada', 'Aleosan', 'Antipas', 'Arakan', 'Banisilan',
    'Carmen', 'Kabacan', 'Libungan', 'Magpet', 'Makilala', 'Matalam',
    'Midsayap', 'M\'lang', 'Pigkawayan', 'Pikit', 'President Roxas', 'Tulunan',
  ],
  'Davao de Oro': [
    'Nabunturan', 'Compostela', 'Laak', 'Mabini', 'Maco', 'Maragusan',
    'Mawab', 'Monkayo', 'Montevista', 'New Bataan', 'Pantukan',
  ],
  'Davao del Norte': [
    'Tagum City', 'Panabo City', 'Island Garden City of Samal', 'Asuncion',
    'Braulio E. Dujali', 'Carmen', 'Kapalong', 'New Corella', 'San Isidro',
    'Santo Tomas', 'Talaingod',
  ],
  'Davao del Sur': [
    'Davao City', 'Digos City', 'Bansalan', 'Don Marcelino', 'Hagonoy',
    'José Abad Santos', 'Kiblawan', 'Magsaysay', 'Malalag', 'Matanao',
    'Padada', 'Santa Cruz', 'Sulop',
  ],
  'Davao Occidental': [
    'Malita', 'Don Marcelino', 'José Abad Santos', 'Santa Maria', 'Sarangani',
  ],
  'Davao Oriental': [
    'Mati City', 'Baganga', 'Banaybanay', 'Boston', 'Caraga', 'Cateel',
    'Governor Generoso', 'Lupon', 'Manay', 'San Isidro', 'Tarragona',
  ],
  'Dinagat Islands': [
    'San Jose', 'Basilisa', 'Cagdianao', 'Dinagat', 'Libjo', 'Loreto', 'Tubajon',
  ],
  'Eastern Samar': [
    'Borongan City', 'Arteche', 'Balangiga', 'Balangkayan', 'Can-avid',
    'Dolores', 'General MacArthur', 'Giporlos', 'Guiuan', 'Hernani',
    'Jipapad', 'Lawaan', 'Llorente', 'Maslog', 'Maydolong', 'Mercedes',
    'Oras', 'Quinapondan', 'Salcedo', 'San Julian', 'San Policarpo', 'Sulat', 'Taft',
  ],
  'Guimaras': [
    'Jordan', 'Buenavista', 'Nueva Valencia', 'San Lorenzo', 'Sibunag',
  ],
  'Ifugao': [
    'Lagawe', 'Alfonso Lista', 'Asipulo', 'Banaue', 'Hingyon', 'Hungduan',
    'Kiangan', 'Lamut', 'Mayoyao', 'Tinoc',
  ],
  'Ilocos Norte': [
    'Laoag City', 'Batac City', 'Adams', 'Bacarra', 'Badoc', 'Bangui',
    'Banna', 'Burgos', 'Carasi', 'Currimao', 'Dingras', 'Dumalneg', 'Marcos',
    'Nueva Era', 'Pagudpud', 'Paoay', 'Pasuquin', 'Piddig', 'Pinili',
    'San Nicolas', 'Sarrat', 'Solsona', 'Vintar',
  ],
  'Ilocos Sur': [
    'Vigan City', 'Candon City', 'Alilem', 'Banayoyo', 'Bantay', 'Burgos',
    'Cabugao', 'Caoayan', 'Cervantes', 'Galimuyod', 'Gregorio del Pilar',
    'Lidlidda', 'Magsingal', 'Nagbukel', 'Narvacan', 'Quirino', 'Salcedo',
    'San Emilio', 'San Esteban', 'San Ildefonso', 'San Juan', 'San Vicente',
    'Santa', 'Santa Catalina', 'Santa Cruz', 'Santa Lucia', 'Santa Maria',
    'Santiago', 'Sigay', 'Sinait', 'Sugpon', 'Suyo', 'Tagudin',
  ],
  'Iloilo': [
    'Iloilo City', 'Passi City', 'Ajuy', 'Alimodian', 'Anilao', 'Badiangan',
    'Balasan', 'Banate', 'Barotac Nuevo', 'Barotac Viejo', 'Batad', 'Bingawan',
    'Cabatuan', 'Calinog', 'Carles', 'Concepcion', 'Dingle', 'Dueñas', 'Dumangas',
    'Estancia', 'Guimbal', 'Igbaras', 'Janiuay', 'Lambunao', 'Leganes',
    'Lemery', 'Leon', 'Maasin', 'Miagao', 'Mina', 'New Lucena', 'Oton',
    'Pavia', 'Pototan', 'San Dionisio', 'San Enrique', 'San Joaquin',
    'San Miguel', 'San Rafael', 'Santa Barbara', 'Sara', 'Tigbauan', 'Tubungan', 'Zarraga',
  ],
  'Isabela': [
    'Ilagan City', 'Cauayan City', 'Santiago City', 'Alicia', 'Angadanan',
    'Aurora', 'Benito Soliven', 'Burgos', 'Cabagan', 'Cabatuan', 'Cordon',
    'Delfin Albano', 'Dinapigue', 'Divilacan', 'Echague', 'Gamu', 'Jones',
    'Luna', 'Maconacon', 'Mallig', 'Naguilian', 'Palanan', 'Quezon',
    'Quirino', 'Ramon', 'Reina Mercedes', 'Roxas', 'San Agustin', 'San Guillermo',
    'San Isidro', 'San Manuel', 'San Mariano', 'San Mateo', 'San Pablo',
    'Santa Maria', 'Santo Tomas', 'Tumauini',
  ],
  'Kalinga': [
    'Tabuk City', 'Balbalan', 'Lubuagan', 'Pasil', 'Pinukpuk', 'Rizal', 'Tanudan', 'Tinglayan',
  ],
  'La Union': [
    'San Fernando City', 'Agoo', 'Aringay', 'Bacnotan', 'Bagulin', 'Balaoan',
    'Bangar', 'Bauang', 'Burgos', 'Caba', 'Luna', 'Naguilian', 'Pugo',
    'Rosario', 'San Gabriel', 'San Juan', 'Santo Tomas', 'Santol', 'Sudipen', 'Tubao',
  ],
  'Laguna': [
    'San Pablo City', 'Calamba City', 'Santa Rosa City', 'Biñan City',
    'Cabuyao City', 'Alaminos', 'Bay', 'Cavinti', 'Famy', 'Kalayaan',
    'Liliw', 'Los Baños', 'Luisiana', 'Lumban', 'Mabitac', 'Magdalena',
    'Majayjay', 'Nagcarlan', 'Paete', 'Pagsanjan', 'Pakil', 'Pangil',
    'Pila', 'Rizal', 'San Pedro City', 'Santa Cruz', 'Santa Maria', 'Siniloan', 'Victoria',
  ],
  'Lanao del Norte': [
    'Iligan City', 'Bacolod', 'Baloi', 'Baroy', 'Kapatagan', 'Kauswagan',
    'Kolambugan', 'Lala', 'Linamon', 'Magsaysay', 'Maigo', 'Matungao',
    'Munai', 'Nunungan', 'Pantao Ragat', 'Pantar', 'Poona Piagapo',
    'Salvador', 'Sapad', 'Sultan Naga Dimaporo', 'Tagoloan', 'Tangcal', 'Tubod',
  ],
  'Lanao del Sur': [
    'Marawi City', 'Bacolod-Kalawi', 'Balabagan', 'Balindong', 'Bayang', 'Binidayan',
    'Buadiposo-Buntong', 'Bubong', 'Bumbaran', 'Butig', 'Calanogas', 'Ditsaan-Ramain',
    'Ganassi', 'Kapai', 'Kapatagan', 'Lumba-Bayabao', 'Lumbaca-Unayan', 'Lumbatan',
    'Lumbayanague', 'Madalum', 'Madamba', 'Maguing', 'Malabang', 'Marantao',
    'Marogong', 'Masiu', 'Mulondo', 'Pagayawan', 'Piagapo', 'Picong', 'Poona Bayabao',
    'Pualas', 'Saguiaran', 'Sultan Dumalondong', 'Sultana Uyag Ambolodto', 'Tagoloan II',
    'Tamparan', 'Taraka', 'Tubaran', 'Tugaya', 'Wao',
  ],
  'Leyte': [
    'Tacloban City', 'Baybay City', 'Ormoc City', 'Abuyog', 'Alangalang',
    'Albuera', 'Babatngon', 'Bato', 'Barugo', 'Burauen', 'Calubian', 'Capoocan',
    'Carigara', 'Dagami', 'Dulag', 'Hilongos', 'Hindang', 'Inopacan', 'Isabel',
    'Jaro', 'Javier', 'Julita', 'Kananga', 'La Paz', 'Leyte', 'MacArthur',
    'Mahaplag', 'Matag-ob', 'Matalom', 'Mayorga', 'Merida', 'Palo', 'Palompon',
    'Pastrana', 'San Isidro', 'San Miguel', 'Santa Fe', 'Tabango', 'Tabontabon',
    'Tanauan', 'Tolosa', 'Tunga', 'Villaba',
  ],
  'Maguindanao': [
    'Cotabato City', 'Buluan', 'Datu Abdullah Sangki', 'Datu Anggal Midtimbang',
    'Datu Blah T. Sinsuat', 'Datu Hoffer Ampatuan', 'Datu Odin Sinsuat',
    'Datu Paglas', 'Datu Piang', 'Datu Salibo', 'Datu Saudi-Ampatuan',
    'Datu Unsay', 'General Salipada K. Pendatun', 'Guindulungan', 'Kabuntalan',
    'Mamasapano', 'Mangudadatu', 'Matanog', 'Northern Kabuntalan', 'Pagalungan',
    'Paglat', 'Pandag', 'Parang', 'Rajah Buayan', 'Shariff Aguak', 'Shariff Saydona Mustapha',
    'South Upi', 'Sultan Kudarat', 'Sultan Mastura', 'Sultan sa Barongis', 'Talayan', 'Talitay', 'Upi',
  ],
  'Marinduque': [
    'Boac', 'Buenavista', 'Gasan', 'Mogpog', 'Santa Cruz', 'Torrijos',
  ],
  'Masbate': [
    'Masbate City', 'Aroroy', 'Baleno', 'Balud', 'Batuan', 'Cataingan', 'Cawayan',
    'Claveria', 'Dimasalang', 'Esperanza', 'Mandaon', 'Milagros', 'Mobo', 'Monreal',
    'Palanas', 'Pio V. Corpus', 'Placer', 'San Fernando', 'San Jacinto', 'San Pascual',
    'Uson',
  ],
  'Misamis Occidental': [
    'Oroquieta City', 'Ozamiz City', 'Tangub City', 'Aloran', 'Baliangao',
    'Bonifacio', 'Calamba', 'Clarin', 'Concepcion', 'Don Victoriano Chiongbian',
    'Jimenez', 'Lopez Jaena', 'Panaon', 'Plaridel', 'Sapang Dalaga', 'Sinacaban',
    'Tudela',
  ],
  'Misamis Oriental': [
    'Cagayan de Oro City', 'Gingoog City', 'El Salvador City', 'Alubijid',
    'Balingasag', 'Balingoan', 'Binuangan', 'Claveria', 'Gitagum', 'Initao',
    'Jasaan', 'Kinoguitan', 'Lagonglong', 'Laguindingan', 'Libertad', 'Lugait',
    'Magsaysay', 'Manticao', 'Medina', 'Naawan', 'Opol', 'Salay', 'Sugbongcogon',
    'Tagoloan', 'Talisayan', 'Villanueva',
  ],
  'Mountain Province': [
    'Bontoc', 'Barlig', 'Bauko', 'Besao', 'Natonin', 'Paracelis', 'Sabangan', 'Sadanga', 'Sagada', 'Tadian',
  ],
  'Negros Occidental': [
    'Bacolod City', 'Bago City', 'Cadiz City', 'Escalante City', 'Himamaylan City',
    'Kabankalan City', 'La Carlota City', 'Sagay City', 'San Carlos City',
    'Silay City', 'Sipalay City', 'Talisay City', 'Victorias City', 'Binalbagan',
    'Calatrava', 'Candoni', 'Cauayan', 'Don Salvador Benedicto', 'Enrique B. Magalona',
    'Hinigaran', 'Hinoba-an', 'Ilog', 'Isabela', 'Manapla', 'Moises Padilla',
    'Murcia', 'Pontevedra', 'Pulupandan', 'Salvador Benedicto', 'San Enrique',
    'Toboso', 'Valladolid',
  ],
  'Negros Oriental': [
    'Dumaguete City', 'Bais City', 'Bayawan City', 'Canlaon City', 'Guihulngan City',
    'Tanjay City', 'Amlan', 'Ayungon', 'Bacong', 'Basay', 'Bindoy', 'Dauin',
    'Jimalalud', 'La Libertad', 'Mabinay', 'Manjuyod', 'Pamplona', 'San Jose',
    'Santa Catalina', 'Siaton', 'Sibulan', 'Tayasan', 'Valencia', 'Vallehermoso', 'Zamboanguita',
  ],
  'Northern Samar': [
    'Catarman', 'Allen', 'Biri', 'Bobon', 'Capul', 'Catubig', 'Gamay', 'Laoang',
    'Lapinig', 'Las Navas', 'Lavezares', 'Lope de Vega', 'Mapanas', 'Mondragon',
    'Palapag', 'Pambujan', 'Rosario', 'San Antonio', 'San Isidro', 'San Jose',
    'San Roque', 'San Vicente', 'Silvino Lubos', 'Victoria',
  ],
  'Nueva Ecija': [
    'Cabanatuan City', 'Gapan City', 'Muñoz City', 'Palayan City', 'San Jose City',
    'Aliaga', 'Bongabon', 'Cabiao', 'Carranglan', 'Cuyapo', 'Guimba', 'Jaen',
    'Laur', 'Licab', 'Llanera', 'Lupao', 'Nampicuan', 'Pantabangan', 'Peñaranda',
    'Quezon', 'Rizal', 'San Antonio', 'San Isidro', 'San Leonardo', 'Santa Rosa',
    'Santo Domingo', 'Talavera', 'Talugtug', 'Zaragoza',
  ],
  'Nueva Vizcaya': [
    'Bayombong', 'Ambaguio', 'Aritao', 'Bagabag', 'Bambang', 'Diadi', 'Dupax del Norte',
    'Dupax del Sur', 'Kasibu', 'Kayapa', 'Quezon', 'Santa Fe', 'Solano', 'Villaverde',
  ],
  'Occidental Mindoro': [
    'Mamburao', 'Abra de Ilog', 'Calintaan', 'Looc', 'Lubang', 'Magsaysay',
    'Paluan', 'Rizal', 'Sablayan', 'San Jose', 'Santa Cruz',
  ],
  'Oriental Mindoro': [
    'Calapan City', 'Baco', 'Bansud', 'Bongabong', 'Bulalacao', 'Gloria',
    'Mansalay', 'Naujan', 'Pinamalayan', 'Pola', 'Puerto Galera', 'Roxas',
    'San Teodoro', 'Socorro', 'Victoria',
  ],
  'Palawan': [
    'Puerto Princesa City', 'Aborlan', 'Agutaya', 'Araceli', 'Balabac', 'Bataraza',
    'Brooke\'s Point', 'Buliluyan', 'Cagayancillo', 'Coron', 'Culion', 'Cuyo',
    'Dumaran', 'El Nido', 'Española', 'Kalayaan', 'Linapacan', 'Magsaysay',
    'Narra', 'Quezon', 'Rizal', 'Roxas', 'San Vicente', 'Sofronio Española', 'Taytay',
  ],
  'Pampanga': [
    'Angeles City', 'San Fernando City', 'Apalit', 'Arayat', 'Bacolor',
    'Candaba', 'Floridablanca', 'Guagua', 'Lubao', 'Mabalacat City', 'Macabebe',
    'Magalang', 'Masantol', 'Mexico', 'Minalin', 'Porac', 'San Luis', 'San Simon',
    'Santa Ana', 'Santa Rita', 'Santo Tomas', 'Sasmuan',
  ],
  'Pangasinan': [
    'Dagupan City', 'San Carlos City', 'Urdaneta City', 'Alaminos City',
    'Agno', 'Aguilar', 'Alcala', 'Anda', 'Asingan', 'Balungao', 'Bani',
    'Basista', 'Bautista', 'Bayambang', 'Binalonan', 'Binmaley', 'Bolinao',
    'Bugallon', 'Burgos', 'Calasiao', 'Dasol', 'Infanta', 'Labrador', 'Laoac',
    'Lingayen', 'Mabini', 'Malasiqui', 'Manaoag', 'Mangaldan', 'Mangatarem',
    'Mapandan', 'Natividad', 'Pozorrubio', 'Rosales', 'San Fabian', 'San Jacinto',
    'San Manuel', 'San Nicolas', 'San Quintin', 'Santa Barbara', 'Santa Maria',
    'Santo Tomas', 'Sison', 'Sual', 'Tayug', 'Umingan', 'Urbiztondo',
    'Villasis',
  ],
  'Quezon': [
    'Lucena City', 'Tayabas City', 'Agdangan', 'Alabat', 'Atimonan', 'Buenavista',
    'Burdeos', 'Calauag', 'Candelaria', 'Catanauan', 'Dolores', 'General Luna',
    'General Nakar', 'Guinayangan', 'Gumaca', 'Infanta', 'Jomalig', 'Lopez',
    'Lucban', 'Macalelon', 'Mauban', 'Mulanay', 'Padre Burgos', 'Pagbilao',
    'Panukulan', 'Patnanungan', 'Perez', 'Pitogo', 'Plaridel', 'Polillo',
    'Quezon', 'Real', 'Sampaloc', 'San Andres', 'San Antonio', 'San Francisco',
    'San Narciso', 'Sariaya', 'Tagkawayan', 'Tiaong', 'Unisan',
  ],
  'Quirino': [
    'Cabarroguis', 'Aglipay', 'Diffun', 'Maddela', 'Nagtipunan', 'Saguday',
  ],
  'Rizal': [
    'Antipolo City', 'Angono', 'Baras', 'Binangonan', 'Cainta', 'Cardona',
    'Jala-Jala', 'Morong', 'Pililla', 'Rodriguez', 'San Mateo', 'Tanay',
    'Taytay', 'Teresa',
  ],
  'Romblon': [
    'Romblon', 'Alcantara', 'Banton', 'Cajidiocan', 'Calatrava', 'Concepcion',
    'Corcuera', 'Ferrol', 'Looc', 'Magdiwang', 'Odiongan', 'San Agustin',
    'San Andres', 'San Fernando', 'San Jose', 'Santa Fe', 'Santa Maria',
  ],
  'Samar (Western Samar)': [
    'Catbalogan City', 'Calbayog City', 'Almagro', 'Basey', 'Calbiga',
    'Daram', 'Gandara', 'Hinabangan', 'Jiabong', 'Marabut', 'Matuguinao',
    'Motiong', 'Paranas', 'Pinabacdao', 'San Jorge', 'San Jose de Buan',
    'San Sebastian', 'Santa Rita', 'Santo Niño', 'Sta. Margarita', 'Tagapul-an',
    'Talalora', 'Tarangnan', 'Villareal', 'Zumarraga',
  ],
  'Sarangani': [
    'Alabel', 'Glan', 'Kiamba', 'Maasim', 'Maitum', 'Malapatan', 'Malungon',
  ],
  'Siquijor': [
    'Siquijor', 'Enrique Villanueva', 'Larena', 'Lazi', 'Maria', 'San Juan',
  ],
  'Sorsogon': [
    'Sorsogon City', 'Barcelona', 'Bulan', 'Bulusan', 'Casiguran', 'Castilla',
    'Donsol', 'Gubat', 'Irosin', 'Juban', 'Magallanes', 'Matnog', 'Pilar',
    'Prieto Diaz', 'Santa Magdalena', 'Santo Domingo',
  ],
  'South Cotabato': [
    'General Santos City', 'Koronadal City', 'Banga', 'Lake Sebu', 'Norala',
    'Polomolok', 'Santo Niño', 'Surallah', 'T\'Boli', 'Tampakan', 'Tantangan', 'Tupi',
  ],
  'Southern Leyte': [
    'Maasin City', 'Anahawan', 'Bontoc', 'Hinunangan', 'Hinundayan', 'Libagon',
    'Liloan', 'Limasawa', 'Macrohon', 'Malitbog', 'Padre Burgos', 'Pintuyan',
    'Saint Bernard', 'San Francisco', 'San Juan', 'San Ricardo', 'Silago', 'Sogod', 'Tomas Oppus',
  ],
  'Sultan Kudarat': [
    'Tacurong City', 'Bagumbayan', 'Columbio', 'Esperanza', 'Isulan',
    'Kalamansig', 'Lambayong', 'Lebak', 'Lutayan', 'Palimbang', 'President Quirino',
    'Senator Ninoy Aquino',
  ],
  'Sulu': [
    'Jolo', 'Hadji Panglima Tahil', 'Indanan', 'Kalingalan Caluang', 'Lugus',
    'Luuk', 'Maimbung', 'Old Panamao', 'Omar', 'Pandami', 'Panglima Estino',
    'Pangutaran', 'Parang', 'Pata', 'Patikul', 'Siasi', 'Talipao', 'Tapul', 'Tongkil',
  ],
  'Surigao del Norte': [
    'Surigao City', 'Alegria', 'Bacuag', 'Burgos', 'Claver', 'Dapa',
    'Del Carmen', 'General Luna', 'Gigaquit', 'Mainit', 'Malimono', 'Pilar',
    'Placer', 'San Benito', 'San Francisco', 'San Isidro', 'Santa Monica',
    'Sison', 'Socorro', 'Tagana-an', 'Tubod',
  ],
  'Surigao del Sur': [
    'Bislig City', 'Tandag City', 'Barobo', 'Bayabas', 'Cagwait', 'Cantilan',
    'Carmen', 'Carrascal', 'Cortes', 'Hinatuan', 'Lanuza', 'Lianga',
    'Lingig', 'Madrid', 'Marihatag', 'San Agustin', 'San Miguel', 'Tagbina', 'Tago',
  ],
  'Tarlac': [
    'Tarlac City', 'Anao', 'Bamban', 'Camiling', 'Capas', 'Concepcion',
    'Gerona', 'La Paz', 'Mayantoc', 'Moncada', 'Paniqui', 'Pura', 'Ramos',
    'San Clemente', 'San Jose', 'San Manuel', 'Santa Ignacia', 'Victoria',
  ],
  'Tawi-Tawi': [
    'Bongao', 'Languyan', 'Mapun', 'Panglima Sugala', 'Sapa-Sapa', 'Sibutu', 'Simunul', 'Sitangkai',
    'South Ubian', 'Tandubas', 'Turtle Islands',
  ],
  'Zambales': [
    'Olongapo City', 'Botolan', 'Cabangan', 'Candelaria', 'Castillejos', 'Iba',
    'Masinloc', 'Palauig', 'San Antonio', 'San Felipe', 'San Marcelino',
    'San Narciso', 'Santa Cruz', 'Subic',
  ],
  'Zamboanga del Norte': [
    'Dipolog City', 'Dapitan City', 'Baliguian', 'Godod', 'Gutalac', 'Jose Dalman',
    'Kalawit', 'Katipunan', 'La Libertad', 'Labason', 'Liloy', 'Manukan',
    'Mutia', 'Piñan', 'Polanco', 'President Manuel A. Roxas', 'Rizal', 'Salug',
    'San Miguel', 'Sergio Osmeña Sr.', 'Siayan', 'Sibuco', 'Sibutad', 'Sindangan',
    'Siocon', 'Sirawai', 'Tampilisan',
  ],
  'Zamboanga del Sur': [
    'Pagadian City', 'Zamboanga City', 'Aurora', 'Bayog', 'Dimataling', 'Dinas',
    'Dumalinao', 'Dumingag', 'Guipos', 'Josefina', 'Kumalarang', 'Labangan',
    'Lakewood', 'Lapuyan', 'Mahayag', 'Margosatubig', 'Midsalip', 'Molave',
    'Pitogo', 'Ramon Magsaysay', 'San Miguel', 'San Pablo', 'Sominot', 'Tabina',
    'Tambulig', 'Tigbao', 'Tukuran', 'Vincenzo A. Sagun',
  ],
  'Zamboanga Sibugay': [
    'Ipil', 'Alicia', 'Buug', 'Diplahan', 'Imelda', 'Kabasalan', 'Mabuhay',
    'Malangas', 'Naga', 'Olutanga', 'Payao', 'Roseller Lim', 'Siay', 'Talusan',
    'Titay', 'Tungawan',
  ],
}

export const provinceList = Object.keys(provinces)
